workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          cd app
          flutter pub get
      - name: Build APK
        script: |
          cd app
          flutter build apk --release
    artifacts:
      - app/build/app/outputs/flutter-apk/app-release.apk
